### ISSUE TITLE
API para compartilhamento de dados

### ISSUE THREAD

**Issue by marioidival** [olhoneles/olhoneles#5]
Conversando no grupo com a galera lá:
https://www.facebook.com/groups/osadpa/477507865688079/

Pensei, se existir uma api do olhoneles, com gastos, nomes e etc... e compartilha-los no Facebook, Twitter, Google+...

Será se essa ideia, seria boa?

**Comment by marcelometal** [comment]
http://olhoneles.org/api/v0/
